# Generated by Django 5.0.4 on 2024-04-19 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/a')),
                ('background', models.ImageField(upload_to='banners/a')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('link_title', models.CharField(max_length=70)),
                ('link', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BannerDestacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/destacado')),
                ('background', models.ImageField(upload_to='banners/destacado')),
                ('title', models.CharField(max_length=70)),
                ('subtitle', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('link_title', models.CharField(max_length=70)),
                ('link', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=41)),
                ('logo', models.ImageField(upload_to='brands/logos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.IntegerField()),
                ('nombre_comercial', models.CharField(max_length=60)),
                ('razon_social', models.CharField(max_length=60)),
                ('direccion_social', models.CharField(max_length=80)),
                ('tipo_via', models.CharField(max_length=28)),
                ('referencia_social', models.CharField(max_length=80)),
                ('nro_dpto', models.CharField(max_length=21)),
                ('dpto', models.CharField(max_length=49)),
                ('prov', models.CharField(max_length=49)),
                ('dist', models.CharField(max_length=49)),
                ('first_name', models.CharField(max_length=28)),
                ('last_name', models.CharField(max_length=28)),
                ('middle_name', models.CharField(max_length=28)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('job_title', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=35)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('icon', models.ImageField(upload_to='reasons/icons')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('code', models.CharField(max_length=35)),
                ('price_no_offer', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('picture', models.ImageField(upload_to='products/pictures')),
                ('description', models.TextField()),
                ('stock', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.brand')),
            ],
        ),
    ]
