# Generated by Django 5.0.4 on 2024-04-19 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_reason_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannera',
            name='background',
            field=models.ImageField(upload_to='static/images/banners/a'),
        ),
        migrations.AlterField(
            model_name='bannera',
            name='image',
            field=models.ImageField(upload_to='static/images/banners/a'),
        ),
        migrations.AlterField(
            model_name='bannerdestacado',
            name='background',
            field=models.ImageField(upload_to='static/images/banners/destacado'),
        ),
        migrations.AlterField(
            model_name='bannerdestacado',
            name='image',
            field=models.ImageField(upload_to='static/images/banners/destacado'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.FileField(upload_to='static/images/brands/logos', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to='static/images/products/pictures'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='icon',
            field=models.FileField(upload_to='static/images/reasons/icons', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])]),
        ),
    ]
