# Generated by Django 5.0.4 on 2024-04-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_menucategory_subsystem_system_menusubcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsystem',
            name='idSubsystem',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='system',
            name='idSystem',
            field=models.CharField(max_length=3),
        ),
    ]
