# Generated by Django 5.0.4 on 2024-04-20 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_subsystem_idsubsystem_alter_system_idsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='web.currencytype'),
        ),
        migrations.AlterField(
            model_name='menusubcategory',
            name='idCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='web.menucategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='web.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='idSubsystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsystems', to='web.subsystem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='idSystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systems', to='web.system'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/products/pictures'),
        ),
        migrations.AlterField(
            model_name='subsystem',
            name='idSystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsystems', to='web.system'),
        ),
    ]
