# Generated by Django 5.0.4 on 2024-04-20 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_rename_idsystem_subsystem_system_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='account_currency',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='menusubcategory',
            old_name='idCategory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='idSubsystem',
            new_name='subsystem',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='idSystem',
            new_name='system',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='idMenuCategory',
        ),
        migrations.RemoveField(
            model_name='menusubcategory',
            name='idMenuSubcategory',
        ),
    ]
