# Generated by Django 5.0.4 on 2024-04-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_rename_category_menusubcategory_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='line',
            field=models.SmallIntegerField(default=0),
        ),
    ]
